sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PWsJ+QvnVmJB/bLvo8HaKMffevuN/Ykthsy9a5gzjcq0JsRa5arz+rl/n74hEqKyJemSML+IL7OyWwdMkjoECahNDwwNF2FFpg70SolKOrgsY+7ULR12xE3hHCdL1Qp9vhmhC7Umpm4sbVUEMH93MZBCv7zCivzjvlD2Kw0m4C6CgjUlItn5x0g99NtZb7b4LfwOlWIKMwxFPkPKruc9XM4nkiWmaqbPzFQ31Uw291eucD2UfbxIjS3HjGmTpfYWOonFhGkRBTB26wEPe3fuEnm++E9E6msoZ55PPCwBV5D92jpr8YUw/ARhKDk6HXOt51dfEeorgjMmLPLXeys+cxDUSqOUDipMmfefui9igousuqHa3iFR1nML++RFiwqJzu8ZWSWLgOCLq0IoN1iG4IXvQm4h9yAddE0BClgKivLHvqXHvXsmRk31Ls3nXbO665EcwCZEsYHI6Yd6u9Dm4oHCuI9EvF1mR61HN3X5qExuM3GSpC0DYXwwv7VxoJKxAMva97KMiFFHxHy72lY+Fp/fvguyO8tlQhnE8q9Ul6gKm9zpa4GLcOy3HwGlN7nanrmRDa89f+wh+UMoz6a6KKPTOKEV84Idvixq/RGk8GmchT7xj1ppE1QfpBTSTzD9nwpy3nm1+S/htrVKz7VwpmAqJ4H1UWQqHiL2ST+dNSo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Summer_166
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy